export * as auth from './auth';//把所有auth相关的函数命名为auth的对象然后导出
export * as facility from './facility';
export * as user from './user';
export * as vendor from './vendor';
export * as order from './order';
export * as state from './state';
export * as character from './character';
export * as log from './log';
export * as resetPassword from './reset-password';
export * as inviteCode from './invite-code';
export * as profile from './profile';
export * as dashboard from './dashboard';
export * as warning from './warning';